// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddFilesFromFilelist
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidAddFilesFromFilelistPackageString = "ae391686-d697-47cd-a373-64496921fba8";
        public static Guid guidAddFilesFromFilelistPackage = new Guid(guidAddFilesFromFilelistPackageString);

        public const string guidAddFilesFromFilelistPackageCmdSetString = "27e5c22d-9dfb-45a8-8374-0984b9ea9eaa";
        public static Guid guidAddFilesFromFilelistPackageCmdSet = new Guid(guidAddFilesFromFilelistPackageCmdSetString);

        public const string guidImagesString = "fc205253-fbaf-4205-ac87-77d2dc03f392";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}