// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AddFilesFromFilelist
{
    internal sealed partial class Vsix
    {
        public const string Id = "AddFilesFromFilelist.db05e4d1-fa93-49c9-a6bf-e4e661f31b5b";
        public const string Name = "AddFilesFromFilelist";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "ohtorii";
        public const string Tags = "";
    }
}
